// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TextMentionService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::social_network;

class TextMentionServiceHandler : virtual public TextMentionServiceIf {
 public:
  TextMentionServiceHandler() {
    // Your initialization goes here
  }

  void ComposeTextMentions(std::vector<UserMention> & _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier) {
    // Your implementation goes here
    printf("ComposeTextMentions\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<TextMentionServiceHandler> handler(new TextMentionServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new TextMentionServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

