/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TextUrlService_H
#define TextUrlService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "social_network_types.h"

namespace social_network {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TextUrlServiceIf {
 public:
  virtual ~TextUrlServiceIf() {}
  virtual void ComposeTextUrls(TextUrlReturn& _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier) = 0;
};

class TextUrlServiceIfFactory {
 public:
  typedef TextUrlServiceIf Handler;

  virtual ~TextUrlServiceIfFactory() {}

  virtual TextUrlServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TextUrlServiceIf* /* handler */) = 0;
};

class TextUrlServiceIfSingletonFactory : virtual public TextUrlServiceIfFactory {
 public:
  TextUrlServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TextUrlServiceIf>& iface) : iface_(iface) {}
  virtual ~TextUrlServiceIfSingletonFactory() {}

  virtual TextUrlServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TextUrlServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TextUrlServiceIf> iface_;
};

class TextUrlServiceNull : virtual public TextUrlServiceIf {
 public:
  virtual ~TextUrlServiceNull() {}
  void ComposeTextUrls(TextUrlReturn& /* _return */, const int64_t /* req_id */, const std::string& /* text */, const std::map<std::string, std::string> & /* carrier */) {
    return;
  }
};

typedef struct _TextUrlService_ComposeTextUrls_args__isset {
  _TextUrlService_ComposeTextUrls_args__isset() : req_id(false), text(false), carrier(false) {}
  bool req_id :1;
  bool text :1;
  bool carrier :1;
} _TextUrlService_ComposeTextUrls_args__isset;

class TextUrlService_ComposeTextUrls_args {
 public:

  TextUrlService_ComposeTextUrls_args(const TextUrlService_ComposeTextUrls_args&);
  TextUrlService_ComposeTextUrls_args& operator=(const TextUrlService_ComposeTextUrls_args&);
  TextUrlService_ComposeTextUrls_args() : req_id(0), text() {
  }

  virtual ~TextUrlService_ComposeTextUrls_args() throw();
  int64_t req_id;
  std::string text;
  std::map<std::string, std::string>  carrier;

  _TextUrlService_ComposeTextUrls_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_text(const std::string& val);

  void __set_carrier(const std::map<std::string, std::string> & val);

  bool operator == (const TextUrlService_ComposeTextUrls_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(text == rhs.text))
      return false;
    if (!(carrier == rhs.carrier))
      return false;
    return true;
  }
  bool operator != (const TextUrlService_ComposeTextUrls_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TextUrlService_ComposeTextUrls_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TextUrlService_ComposeTextUrls_pargs {
 public:


  virtual ~TextUrlService_ComposeTextUrls_pargs() throw();
  const int64_t* req_id;
  const std::string* text;
  const std::map<std::string, std::string> * carrier;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TextUrlService_ComposeTextUrls_result__isset {
  _TextUrlService_ComposeTextUrls_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _TextUrlService_ComposeTextUrls_result__isset;

class TextUrlService_ComposeTextUrls_result {
 public:

  TextUrlService_ComposeTextUrls_result(const TextUrlService_ComposeTextUrls_result&);
  TextUrlService_ComposeTextUrls_result& operator=(const TextUrlService_ComposeTextUrls_result&);
  TextUrlService_ComposeTextUrls_result() {
  }

  virtual ~TextUrlService_ComposeTextUrls_result() throw();
  TextUrlReturn success;
  ServiceException se;

  _TextUrlService_ComposeTextUrls_result__isset __isset;

  void __set_success(const TextUrlReturn& val);

  void __set_se(const ServiceException& val);

  bool operator == (const TextUrlService_ComposeTextUrls_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const TextUrlService_ComposeTextUrls_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TextUrlService_ComposeTextUrls_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TextUrlService_ComposeTextUrls_presult__isset {
  _TextUrlService_ComposeTextUrls_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _TextUrlService_ComposeTextUrls_presult__isset;

class TextUrlService_ComposeTextUrls_presult {
 public:


  virtual ~TextUrlService_ComposeTextUrls_presult() throw();
  TextUrlReturn* success;
  ServiceException se;

  _TextUrlService_ComposeTextUrls_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TextUrlServiceClient : virtual public TextUrlServiceIf {
 public:
  TextUrlServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TextUrlServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposeTextUrls(TextUrlReturn& _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  void send_ComposeTextUrls(const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  void recv_ComposeTextUrls(TextUrlReturn& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TextUrlServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TextUrlServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TextUrlServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ComposeTextUrls(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TextUrlServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TextUrlServiceIf> iface) :
    iface_(iface) {
    processMap_["ComposeTextUrls"] = &TextUrlServiceProcessor::process_ComposeTextUrls;
  }

  virtual ~TextUrlServiceProcessor() {}
};

class TextUrlServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TextUrlServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TextUrlServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TextUrlServiceIfFactory > handlerFactory_;
};

class TextUrlServiceMultiface : virtual public TextUrlServiceIf {
 public:
  TextUrlServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TextUrlServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TextUrlServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TextUrlServiceIf> > ifaces_;
  TextUrlServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TextUrlServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ComposeTextUrls(TextUrlReturn& _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ComposeTextUrls(_return, req_id, text, carrier);
    }
    ifaces_[i]->ComposeTextUrls(_return, req_id, text, carrier);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TextUrlServiceConcurrentClient : virtual public TextUrlServiceIf {
 public:
  TextUrlServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TextUrlServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposeTextUrls(TextUrlReturn& _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  int32_t send_ComposeTextUrls(const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  void recv_ComposeTextUrls(TextUrlReturn& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
