/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TextMentionService_H
#define TextMentionService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "social_network_types.h"

namespace social_network {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TextMentionServiceIf {
 public:
  virtual ~TextMentionServiceIf() {}
  virtual void ComposeTextMentions(std::vector<UserMention> & _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier) = 0;
};

class TextMentionServiceIfFactory {
 public:
  typedef TextMentionServiceIf Handler;

  virtual ~TextMentionServiceIfFactory() {}

  virtual TextMentionServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TextMentionServiceIf* /* handler */) = 0;
};

class TextMentionServiceIfSingletonFactory : virtual public TextMentionServiceIfFactory {
 public:
  TextMentionServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TextMentionServiceIf>& iface) : iface_(iface) {}
  virtual ~TextMentionServiceIfSingletonFactory() {}

  virtual TextMentionServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TextMentionServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TextMentionServiceIf> iface_;
};

class TextMentionServiceNull : virtual public TextMentionServiceIf {
 public:
  virtual ~TextMentionServiceNull() {}
  void ComposeTextMentions(std::vector<UserMention> & /* _return */, const int64_t /* req_id */, const std::string& /* text */, const std::map<std::string, std::string> & /* carrier */) {
    return;
  }
};

typedef struct _TextMentionService_ComposeTextMentions_args__isset {
  _TextMentionService_ComposeTextMentions_args__isset() : req_id(false), text(false), carrier(false) {}
  bool req_id :1;
  bool text :1;
  bool carrier :1;
} _TextMentionService_ComposeTextMentions_args__isset;

class TextMentionService_ComposeTextMentions_args {
 public:

  TextMentionService_ComposeTextMentions_args(const TextMentionService_ComposeTextMentions_args&);
  TextMentionService_ComposeTextMentions_args& operator=(const TextMentionService_ComposeTextMentions_args&);
  TextMentionService_ComposeTextMentions_args() : req_id(0), text() {
  }

  virtual ~TextMentionService_ComposeTextMentions_args() throw();
  int64_t req_id;
  std::string text;
  std::map<std::string, std::string>  carrier;

  _TextMentionService_ComposeTextMentions_args__isset __isset;

  void __set_req_id(const int64_t val);

  void __set_text(const std::string& val);

  void __set_carrier(const std::map<std::string, std::string> & val);

  bool operator == (const TextMentionService_ComposeTextMentions_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(text == rhs.text))
      return false;
    if (!(carrier == rhs.carrier))
      return false;
    return true;
  }
  bool operator != (const TextMentionService_ComposeTextMentions_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TextMentionService_ComposeTextMentions_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TextMentionService_ComposeTextMentions_pargs {
 public:


  virtual ~TextMentionService_ComposeTextMentions_pargs() throw();
  const int64_t* req_id;
  const std::string* text;
  const std::map<std::string, std::string> * carrier;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TextMentionService_ComposeTextMentions_result__isset {
  _TextMentionService_ComposeTextMentions_result__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _TextMentionService_ComposeTextMentions_result__isset;

class TextMentionService_ComposeTextMentions_result {
 public:

  TextMentionService_ComposeTextMentions_result(const TextMentionService_ComposeTextMentions_result&);
  TextMentionService_ComposeTextMentions_result& operator=(const TextMentionService_ComposeTextMentions_result&);
  TextMentionService_ComposeTextMentions_result() {
  }

  virtual ~TextMentionService_ComposeTextMentions_result() throw();
  std::vector<UserMention>  success;
  ServiceException se;

  _TextMentionService_ComposeTextMentions_result__isset __isset;

  void __set_success(const std::vector<UserMention> & val);

  void __set_se(const ServiceException& val);

  bool operator == (const TextMentionService_ComposeTextMentions_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(se == rhs.se))
      return false;
    return true;
  }
  bool operator != (const TextMentionService_ComposeTextMentions_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TextMentionService_ComposeTextMentions_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TextMentionService_ComposeTextMentions_presult__isset {
  _TextMentionService_ComposeTextMentions_presult__isset() : success(false), se(false) {}
  bool success :1;
  bool se :1;
} _TextMentionService_ComposeTextMentions_presult__isset;

class TextMentionService_ComposeTextMentions_presult {
 public:


  virtual ~TextMentionService_ComposeTextMentions_presult() throw();
  std::vector<UserMention> * success;
  ServiceException se;

  _TextMentionService_ComposeTextMentions_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TextMentionServiceClient : virtual public TextMentionServiceIf {
 public:
  TextMentionServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TextMentionServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposeTextMentions(std::vector<UserMention> & _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  void send_ComposeTextMentions(const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  void recv_ComposeTextMentions(std::vector<UserMention> & _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TextMentionServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TextMentionServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TextMentionServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ComposeTextMentions(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TextMentionServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TextMentionServiceIf> iface) :
    iface_(iface) {
    processMap_["ComposeTextMentions"] = &TextMentionServiceProcessor::process_ComposeTextMentions;
  }

  virtual ~TextMentionServiceProcessor() {}
};

class TextMentionServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TextMentionServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TextMentionServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TextMentionServiceIfFactory > handlerFactory_;
};

class TextMentionServiceMultiface : virtual public TextMentionServiceIf {
 public:
  TextMentionServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TextMentionServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TextMentionServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TextMentionServiceIf> > ifaces_;
  TextMentionServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TextMentionServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ComposeTextMentions(std::vector<UserMention> & _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ComposeTextMentions(_return, req_id, text, carrier);
    }
    ifaces_[i]->ComposeTextMentions(_return, req_id, text, carrier);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TextMentionServiceConcurrentClient : virtual public TextMentionServiceIf {
 public:
  TextMentionServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TextMentionServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ComposeTextMentions(std::vector<UserMention> & _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  int32_t send_ComposeTextMentions(const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier);
  void recv_ComposeTextMentions(std::vector<UserMention> & _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
