// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "TextUrlService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::social_network;

class TextUrlServiceHandler : virtual public TextUrlServiceIf {
 public:
  TextUrlServiceHandler() {
    // Your initialization goes here
  }

  void ComposeTextUrls(TextUrlReturn& _return, const int64_t req_id, const std::string& text, const std::map<std::string, std::string> & carrier) {
    // Your implementation goes here
    printf("ComposeTextUrls\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<TextUrlServiceHandler> handler(new TextUrlServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new TextUrlServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

